[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install -y python3-pip libpango1.0-dev libcairo2-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libwayland-dev libxkbcommon-dev wayland-protocols libdbus-1-dev && pip3 install cmake",
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "apt-get update && apt-get install -y python3-pip libpango1.0-dev libcairo2-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libwayland-dev libxkbcommon-dev wayland-protocols libdbus-1-dev && pip3 install cmake",
]
